baseURL = "https://ckondisetty.github.io/literate-palm-tree/"
title = "Chakradhar Sai Kondisetty"
theme = "PaperMod"

[params]
  defaultTheme = "light"

[params.profileMode]
  enabled = true
  title = "Chakradhar Sai Kondisetty"
  imageUrl = "" # Leave blank or put your photo filename here
  
  [[params.profileMode.buttons]]
    url = "/posts"
    text = "Artifacts"