baseURL = "https://ckondisetty.github.io/literate-palm-tree/"
title = "Chakradhar Sa Kondisetty"
theme = "PaperMod"

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  disableThemeToggle = true
  mainSections = ["posts"]
  cacheBust = "v1"

[menu]
  [[menu.main]]
    name = "Artifacts"
    url = "/posts/"
    weight = 1