baseURL = "https://ckondisetty.github.io/literate-palm-tree/"
title = "Chakradhar Sai Kondisetty"
theme = "PaperMod"

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  disableThemeToggle = true
  mainSections = ["posts"]

[menu]
  main = [
    {name = "Artifacts", url = "/posts/", weight = 1}
  ]